# Generated by Django 5.0.6 on 2024-06-27 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_rename_meeting_meetingminute_remove_attending_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        
    ]
