# Generated by Django 5.0.6 on 2024-06-27 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_create_tablemeeting_create'),
    ]

    
