# Generated by Django 5.0.6 on 2024-07-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_remove_tablemeeting_create_tablemeeting_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='create',
        ),
        migrations.AlterField(
            model_name='tablemeeting',
            name='title',
            field=models.CharField(choices=[('General', 'General Meeting'), ('Board', 'Board Meeting'), ('Staff', 'Staff Meeting')], max_length=200),
        ),
    ]
