# Generated by Django 5.0.6 on 2024-07-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_alter_meetingminute_action_items_decisions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingminute',
            name='action_items_decisions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingminute',
            name='agenda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingminute',
            name='discussion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablemeeting',
            name='description',
            field=models.TextField(),
        ),
    ]
