# Generated by Django 5.0.6 on 2024-07-03 05:
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_alter_meetingminute_action_items_decisions_and_more'),
    ]

    