# Generated by Django 5.0.6 on 2024-07-03 06:32

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_alter_meetingminute_action_items_decisions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingminute',
            name='action_items_decisions',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingminute',
            name='agenda',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingminute',
            name='discussion',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablemeeting',
            name='description',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
    ]
