# Generated by Django 4.2.14 on 2024-07-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0013_tablemeeting_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='attending',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
