# Generated by Django 4.2.14 on 2024-07-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0014_attending_pdf_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='attending',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
